---
- hosts: localhost
  gather_facts: no
  become: true

  tasks:
  - name: Check for qemu-kvm
    apt:
       name: qemu-kvm
       state: present
      
  - name: Check for libvirt packages and ovs
    apt:
     name: "{{ item }}"
     state: present
    with_items:
       - libvirt-bin
       - virt-manager
       - virt-viewer
       - virtinst  
       - openvswitch-switch
   
  - name: Make sure ubuntu image exists
    docker_image:
      name: ubuntu
      state: present 
  
  - name: Build an image using dockerfile
    docker_image:
      path: "{{playbook_dir}}"
      name: firewall_image
      state: present 

  - name:
    command: sudo ansible-playbook createVM_image.yml
