- hosts: localhost
  gather_facts: no
  become: true
  vars:
    var1: "{{tenant_name}}"
  tasks:

  - name: read the vars_file
    include_vars:
      file: "{{playbook_dir}}/{{var1}}_device_inventory.yml"
      name: names

  - name: Delete namespaces
    command: sudo ip netns del "{{ item }}"
    with_items:
      - "{{ names.Namespace_names }}"
